model_config:
model_name: RandomForest
n_estimators: 100
max_features: 5
min_samples_split: 2
min_samples_leaf: 1
max_depth: 50
bootstrap: True
target: Survived
cols_to_remove:
  - PassengerId
  - Name
  - Ticket
  - Cabin